# Generated by infrastructure/scripts/generate-integration-moved-blocks.py

moved {
  from = aws_apigatewayv2_integration.integrations["admin_cognito_users_list"]
  to   = aws_apigatewayv2_integration.integrations["admin"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["advisors_create"]
  to   = aws_apigatewayv2_integration.integrations["advisors"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["api_keys_create"]
  to   = aws_apigatewayv2_integration.integrations["api_keys"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["automations_create"]
  to   = aws_apigatewayv2_integration.integrations["automations"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["billing_checkout"]
  to   = aws_apigatewayv2_integration.integrations["billing"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["bots_ai_assistant_disable"]
  to   = aws_apigatewayv2_integration.integrations["bots"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["bulk_send_create"]
  to   = aws_apigatewayv2_integration.integrations["bulk_send"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["apps_list"]
  to   = aws_apigatewayv2_integration.integrations["calendar"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["bots_calling_action"]
  to   = aws_apigatewayv2_integration.integrations["calling"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["campaigns_archive"]
  to   = aws_apigatewayv2_integration.integrations["campaigns"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["catalog_config_get"]
  to   = aws_apigatewayv2_integration.integrations["catalog"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["contacts_create"]
  to   = aws_apigatewayv2_integration.integrations["contacts"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["conversations_bulk_handoff"]
  to   = aws_apigatewayv2_integration.integrations["conversations"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["flow_hooks_submit"]
  to   = aws_apigatewayv2_integration.integrations["flow_hooks"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["flow_runs_get"]
  to   = aws_apigatewayv2_integration.integrations["flows"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["integrations_deliveries"]
  to   = aws_apigatewayv2_integration.integrations["integrations"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["knowledge_delete"]
  to   = aws_apigatewayv2_integration.integrations["knowledge"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["leads_convert"]
  to   = aws_apigatewayv2_integration.integrations["leads"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["macros_create"]
  to   = aws_apigatewayv2_integration.integrations["macros"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["mailrelay_proxy_delete"]
  to   = aws_apigatewayv2_integration.integrations["mailrelay"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["meta_flows_create"]
  to   = aws_apigatewayv2_integration.integrations["meta_flows"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["metrics_advisor_workload"]
  to   = aws_apigatewayv2_integration.integrations["metrics"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["payments_config_get"]
  to   = aws_apigatewayv2_integration.integrations["payments"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["public_api_calls_action"]
  to   = aws_apigatewayv2_integration.integrations["public_api"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["public_calendar_bookings"]
  to   = aws_apigatewayv2_integration.integrations["public_calendar"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["conversations_calls_active"]
  to   = aws_apigatewayv2_integration.integrations["realtime"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["reseller_domain_get"]
  to   = aws_apigatewayv2_integration.integrations["reseller"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["sms_dlr"]
  to   = aws_apigatewayv2_integration.integrations["sms_webhook"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["admin_support_tickets_list"]
  to   = aws_apigatewayv2_integration.integrations["support_tickets"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["bots_telephony_calls_create"]
  to   = aws_apigatewayv2_integration.integrations["telephony"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["templates_create"]
  to   = aws_apigatewayv2_integration.integrations["templates"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["auth_portal_access"]
  to   = aws_apigatewayv2_integration.integrations["tenants"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["voicebot_sessions_create"]
  to   = aws_apigatewayv2_integration.integrations["voicebot"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["webchat_call_accept"]
  to   = aws_apigatewayv2_integration.integrations["webchat"]
}

moved {
  from = aws_apigatewayv2_integration.integrations["webhook_receive"]
  to   = aws_apigatewayv2_integration.integrations["webhook"]
}
