export const TELEPHONY_PRICING_VERSION = "2026-08-08";

const FARGATE_BRIDGE_PER_MINUTE_USD = 0.000411;
const ALB_ACTIVE_CALL_PER_MINUTE_USD = 0.0002;
const LAMBDA_AND_DATA_PER_MINUTE_USD = 0.00013;
const FIXED_INFRA_MONTHLY_USD = 39;
const BASELINE_VOICE_MINUTES_PER_MONTH = 2000;

const PLATFORM_VARIABLE_PER_MINUTE_USD =
  FARGATE_BRIDGE_PER_MINUTE_USD + ALB_ACTIVE_CALL_PER_MINUTE_USD + LAMBDA_AND_DATA_PER_MINUTE_USD;

const PLATFORM_FIXED_PER_MINUTE_USD =
  FIXED_INFRA_MONTHLY_USD / BASELINE_VOICE_MINUTES_PER_MONTH;

export const TELEPHONY_PLATFORM_PER_MINUTE_USD =
  Math.round((PLATFORM_VARIABLE_PER_MINUTE_USD + PLATFORM_FIXED_PER_MINUTE_USD) * 1_000_000) /
  1_000_000;

export const TELEPHONY_RATES = {
  platformPerMinuteUsd: TELEPHONY_PLATFORM_PER_MINUTE_USD,
  telnyxOutboundPerMinuteUsd: 0.005,
  telnyxInboundPerMinuteUsd: 0.0035,
  telnyxRecordingPerMinuteUsd: 0.002,
  openaiInputPer1kTokensUsd: 0.0004,
  openaiOutputPer1kTokensUsd: 0.0016,
  elevenlabsPerCharacterUsd: 0.000003,
} as const;
