#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

from api_gateway_integration_slugs import canonical_slug_keys

ROOT = Path(__file__).resolve().parents[1]
OUT_TF = ROOT / "modules/api-gateway/moved-integrations.tf"


def main() -> None:
    blocks = []
    for slug, key in sorted(canonical_slug_keys().items()):
        if key == slug:
            continue
        blocks.append(
            "moved {\n"
            f'  from = aws_apigatewayv2_integration.integrations["{key}"]\n'
            f'  to   = aws_apigatewayv2_integration.integrations["{slug}"]\n'
            "}"
        )

    OUT_TF.write_text(
        "# Generated by infrastructure/scripts/generate-integration-moved-blocks.py\n\n"
        + "\n\n".join(blocks)
        + "\n"
    )
    print(f"Wrote {len(blocks)} moved blocks to {OUT_TF}")


if __name__ == "__main__":
    main()
